/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.*;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.*;

public class App {

    public static void main(String[] args) throws IOException {
        System.out.println(ronSwansonQuote());
    }

    public static String randomQuote(){
            StringBuffer fileReading = new StringBuffer();
            try {
                Scanner quotesJSON = new Scanner(new File("./assets/recentquotes.json"));
                while (quotesJSON.hasNextLine()) {
                    fileReading.append(quotesJSON.nextLine());
                }
            } catch (FileNotFoundException e) {
                System.out.println("The File was not found");
                System.out.println(e);
            }
            Gson gson = new Gson();
            Quote[] quotes = gson.fromJson(fileReading.toString(), Quote[].class);
            Random randomous = new Random();
            return quotes[randomous.nextInt(quotes.length)].toString();
    }

    public static String ronSwansonQuote(){
        try {
            URL url = new URL("https://ron-swanson-quotes.herokuapp.com/v2/quotes");
            HttpURLConnection con = (HttpURLConnection) url.openConnection();
            BufferedReader reader = new BufferedReader(new InputStreamReader((con.getInputStream())));
            Gson gson = new Gson();
            String[] ronSwanson = gson.fromJson(reader, String[].class);
            Quote ronnie = new Quote(ronSwanson[0]);
            return ronnie.toStringRon();
        }catch (IOException e){
            System.out.println("Can't Get a quote from Ron");
            System.out.println(e);
            return randomQuote();
        }
    }

    public static ArrayList readingTheFile(Quote quote){
        try{
            Gson gson = new Gson();
            JsonReader originalFile = new JsonReader(new FileReader("./assets/recentquotes.json"));
            ArrayList<Quote> quoted = new ArrayList<>();
            originalFile.beginArray();
            while(originalFile.hasNext()){
                Quote quotey = gson.fromJson(originalFile, Quote.class);
                quoted.add(quotey);
            }
            quoted.add(quote);
            originalFile.endArray();
            originalFile.close();
            return quoted;
        } catch (IOException e){
            System.out.println(e);
            return new ArrayList();
        }
    }


    public static void writeFile(ArrayList<Quote> arr){
        try {
            Gson gson = new Gson();
            JsonWriter addIt = new JsonWriter(new FileWriter("./assets/recentquotes.json"));
            addIt.setIndent("  ");
            addIt.beginArray();
            for(Quote quote: arr){
                gson.toJson(quote, Quote.class, addIt);
            }
            addIt.endArray();
            addIt.close();
        } catch (IOException e) {
            System.out.println(e);
        }
    }


}

