/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import java.util.*;
import java.io.File;
import java.io.FileNotFoundException;

public class App {

    public static void main(String[] args) {
        System.out.println(randomQuote());
    }

    public static String randomQuote(){
        StringBuffer fileReading = new StringBuffer();
        try {
            Scanner quotesJSON = new Scanner(new File("./assets/recentquotes.json"));
            while (quotesJSON.hasNextLine()) {
                fileReading.append(quotesJSON.nextLine()); }
        } catch(FileNotFoundException e){
            System.out.println("The File was not found");
            System.out.println(e);
        }
        Gson gson = new Gson();
        Quote[] quotes = gson.fromJson(fileReading.toString(), Quote[].class);
        Random randomous = new Random();
        return quotes[randomous.nextInt(quotes.length)].toString();
    }
}
